### ISSUE TITLE
Error with call_log export

### ISSUE THREAD

**Issue by leancode** [mrrfv/open-android-backup#69]
## Device info

Manufacturer: Google Pixel 4XL
Android version: R(11)
Custom ROM/rooted? Not rooted
Model: /e/ OS 1.7-20230110250404

## System info

Available disk space: +1 Terra
Operating system: Ubuntu 22.04 LTS

---
I am getting this is the cli. Everything before and after seems to be working:
```
Exporting call logs.
Error while accessing provider:call_log
java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.CallLogProvider from (null) (pid=19574, uid=2000) requires android.permission.READ_CALL_LOG or android.permission.WRITE_CALL_LOG
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2374)
	at android.os.Parcel.createException(Parcel.java:2358)
	at android.os.Parcel.readException(Parcel.java:2341)
	at android.os.Parcel.readException(Parcel.java:2283)
	at android.app.IActivityManager$Stub$Proxy.getContentProviderExternal(IActivityManager.java:7962)
	at com.android.commands.content.Content$Command.execute(Content.java:515)
	at com.android.commands.content.Content.main(Content.java:727)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7148)
	at com.android.server.am.ActivityManagerService.getContentProviderExternalUnchecked(ActivityManagerService.java:7604)
	at com.android.server.am.ActivityManagerService.getContentProviderExternal(ActivityManagerService.java:7598)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3767)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2875)

Error while accessing provider:call_log
java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.CallLogProvider from (null) (pid=19589, uid=2000) requires android.permission.READ_CALL_LOG or android.permission.WRITE_CALL_LOG
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2374)
	at android.os.Parcel.createException(Parcel.java:2358)
	at android.os.Parcel.readException(Parcel.java:2341)
	at android.os.Parcel.readException(Parcel.java:2283)
	at android.app.IActivityManager$Stub$Proxy.getContentProviderExternal(IActivityManager.java:7962)
	at com.android.commands.content.Content$Command.execute(Content.java:515)
	at com.android.commands.content.Content.main(Content.java:727)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
---
All required data has been copied from your device and it can now be unplugged.

```

**Comment by mrrfv** [comment]
I'm working on a new version that will get the call logs through the companion app instead of adb, which will fix this issue.

**Comment by mrrfv** [comment]
New version's out! Could you please check if it solved the problem?

**Comment by mrrfv** [comment]
No response, so I assume it's been fixed. Closing this issue.
